import {
  faPaintBrush,
  faChartLine,
  faMoneyBillWave,
  faUserTie,
  faLaptopCode,
  faTruckMoving,
  faUserMd,
  faBalanceScale,
  faQuestionCircle,
  faBriefcase,
  faMicrochip,
  faRobot,
  faServer,
  faCogs,
  faCalculator,
  faCloud,
  faCar,
  faPlane,
  faPhone,
  faFlask,
  faBolt,
  faGem,
  faShoppingCart,
  faStore,
  faUtensils,
  faHospital,
  faGlobe,
  faUniversity,
  faWrench,
  faShieldAlt,
  faChalkboardTeacher,
  faExchangeAlt,
  faIndustry,
  faLeaf,
  faUserGraduate,
  faGlassCheers,
  faSnowflake,
  faNetworkWired,
  faHardHat,
  faGavel,
  faNewspaper,
  faMedkit,
  faMountain,
  faHandHoldingHeart,
  faScroll,
  faPrint,
  faBookOpen,
  faCity,
  faUserCheck,
  faLock,
  faShip,
  faCog,
  faPhoneAlt,
  faSitemap,
  faTags,
  faTint,
  faDumbbell,
  faShoppingBag,
  faWifi,
  faTools,
  faPlug,
  faUtensilSpoon,
  faBalanceScaleRight,
  faBuilding,
  faPlaneDeparture,
  faBullhorn,
} from "@fortawesome/free-solid-svg-icons";

export const sectorMapping = {
  accounting: { displayName: "Accounting", icon: faCalculator },
  advertising: { displayName: "Advertising", icon: faBullhorn },
  agriculture: { displayName: "Agriculture", icon: faLeaf },
  animation: { displayName: "Animation", icon: faPaintBrush },
  architecture: { displayName: "Architecture", icon: faBuilding },
  automobile: { displayName: "Automobile", icon: faCar },
  aviation: { displayName: "Aviation", icon: faPlane },
  bpo: { displayName: "BPO", icon: faPhone },
  banking: { displayName: "Banking", icon: faUniversity },
  brewery: { displayName: "Brewery", icon: faGlassCheers },
  sanitary: { displayName: "Sanitary", icon: faTint },
  chemical: { displayName: "Chemical", icon: faFlask },
  engineering: { displayName: "Engineering", icon: faHardHat },
  "consumer durables": { displayName: "Consumer Durables", icon: faStore },
  courier: { displayName: "Courier", icon: faTruckMoving },
  defence: { displayName: "Defence", icon: faShieldAlt },
  education: { displayName: "Education", icon: faChalkboardTeacher },
  electrical: { displayName: "Electrical", icon: faBolt },
  "export import": { displayName: "Export Import", icon: faExchangeAlt },
  fmcg: { displayName: "FMCG", icon: faShoppingCart },
  "facility management": { displayName: "Facility Management", icon: faBuilding },
  fertilizers: { displayName: "Fertilizers", icon: faIndustry },
  "food processing": { displayName: "Food Processing", icon: faUtensils },
  fresher: { displayName: "Fresher", icon: faUserGraduate },
  "gems jewellery": { displayName: "Gems Jewellery", icon: faGem },
  glass: { displayName: "Glass", icon: faGlassCheers },
  "air conditioning": { displayName: "Air Conditioning", icon: faSnowflake },
  airline: { displayName: "Airline", icon: faPlane },
  networking: { displayName: "Networking", icon: faNetworkWired },
  it: { displayName: "IT", icon: faLaptopCode },
  industrial: { displayName: "Industrial", icon: faWrench },
  insurance: { displayName: "Insurance", icon: faBalanceScaleRight },
  kpo: { displayName: "KPO", icon: faPhoneAlt },
  legal: { displayName: "Legal", icon: faGavel },
  media: { displayName: "Media", icon: faNewspaper },
  dotcom: { displayName: "Dotcom", icon: faGlobe },
  entertainment: { displayName: "Entertainment", icon: faGlobe },
  medical: { displayName: "Medical", icon: faMedkit },
  mining: { displayName: "Mining", icon: faMountain },
  ngo: { displayName: "NGO", icon: faHandHoldingHeart },
  automation: { displayName: "Automation", icon: faRobot },
  "oil and gas": { displayName: "Oil and Gas", icon: faFlask },
  paper: { displayName: "Paper", icon: faScroll },
  pharma: { displayName: "Pharma", icon: faFlask },
  printing: { displayName: "Printing", icon: faPrint },
  publishing: { displayName: "Publishing", icon: faBookOpen },
  "real estate": { displayName: "Real Estate", icon: faCity },
  recruitment: { displayName: "Recruitment", icon: faUserCheck },
  retail: { displayName: "Retail", icon: faStore },
  security: { displayName: "Security", icon: faLock },
  electronics: { displayName: "Electronics", icon: faMicrochip },
  shipping: { displayName: "Shipping", icon: faShip },
  steel: { displayName: "Steel", icon: faCog },
  consulting: { displayName: "Consulting", icon: faUserTie },
  telecom: { displayName: "Telecom", icon: faPhoneAlt },
  textiles: { displayName: "Textiles", icon: faSitemap },
  tyres: { displayName: "Tyres", icon: faTags },
  "water treatment": { displayName: "Water Treatment", icon: faTint },
  "fitness trainer": { displayName: "Fitness Trainer", icon: faDumbbell },
  ecommerce: { displayName: "Ecommerce", icon: faShoppingBag },
  internet: { displayName: "Internet", icon: faWifi },
  "it services": { displayName: "IT Services", icon: faServer },
  healthcare: { displayName: "Healthcare", icon: faHospital },
  "hotels & restaurants": { displayName: "Hotels & Restaurants", icon: faUtensilSpoon },
  "industrial equipment": { displayName: "Industrial Equipment", icon: faWrench },
  power: { displayName: "Power", icon: faBolt },
  "software product": { displayName: "Software Product", icon: faCogs },
  "Medical Services / Hospital" : { displayName: "Medical Services / Hospital", icon: faHospital },
  "construction / engineering": { displayName: "Construction / Engineering", icon: faHardHat },
  "business services": { displayName: "Business Services", icon: faBriefcase },
  "government services": { displayName: "Government Services", icon: faBuilding },
  "transportation / logistics": { displayName: "Transportation / Logistics", icon: faTruckMoving },
  "food & beverage": { displayName: "Food & Beverage", icon: faUtensils },
  "hospitality": { displayName: "Hospitality", icon: faUtensils },
  "construction / real estate": { displayName: "Construction / Real Estate", icon: faBuilding },
  "information technology": { displayName: "Information Technology", icon: faLaptopCode },
  "telecommunications": { displayName: "Telecommunications", icon: faPhone },
  "financial services": { displayName: "Financial Services", icon: faMoneyBillWave },
  "human resources": { displayName: "Human Resources", icon: faUserTie },
  "research & development": { displayName: "Research & Development", icon: faFlask },
  "media & entertainment": { displayName: "Media & Entertainment", icon: faGlobe },
  "legal services": { displayName: "Legal Services", icon: faGavel },
  "it services & consulting": { displayName: "IT Services & Consulting", icon: faLaptopCode },
  "medical services / hospital" : { displayName: "Medical Services / Hospital", icon: faHospital },
  "unknown industry": { displayName: "Unknown Industry", icon: faQuestionCircle },
};
